[package]
name = "ecs-run"
version = "0.2.0"
authors = ["Erik Dal√©n <erik.gustav.dalen@gmail.com>"]

[dependencies]
rusoto_logs = "0.32.0"
rusoto_ecs = "0.32.0"
rusoto_core = "0.32.0"
clap = "2.32.0"
