[package]
name = "ecs-run"
version = "0.2.3"
authors = ["Erik Dal√©n <erik.gustav.dalen@gmail.com>"]
edition = "2018"

[dependencies]
rusoto_logs = "0.36.0"
rusoto_ecs = "0.36.0"
rusoto_core = "0.36.0"
clap = "2.33.0"
